# https://lefthook.dev/configuration/index.html
prepare-commit-msg:
  commands:
    commitizen:
      skip: rebase
      interactive: true
      run: npx cz --hook
      env:
        LEFTHOOK: 0
commit-msg:
  commands:
    "lint commit message":
      run: npx commitlint --edit {1}
pre-commit:
  commands:
    "generate README table of contents":
      skip: rebase
      glob: "(README).{md}"
      run: doctoc {1}
    "detect secrets":
      files: git diff --name-only --diff-filter=d --staged
      run: gitleaks protect --no-banner --staged --redact --verbose 
